<a href="https://colab.research.google.com/github/zhangshutao932/StrataScratch-Data-Transformation/blob/main/Data_Transformation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import json
import pandas as pd

df = pd.read_json("case.json")
df.head()

,EnqueuedTimeUtc,EventName,Payload
0,2021-09-05 08:04:08 UTC,DynamicPrice_Result,"{""provider"":""ApplyDynamicPriceRange"",""offerId""..."
1,2021-08-18 11:43:23 UTC,DynamicPrice_Result,"{""provider"":""ApplyDynamicPricePerOption"",""offe..."
2,2021-09-05 09:04:04 UTC,DynamicPrice_Result,"{""provider"":""ApplyDynamicPriceRange"",""offerId""..."
3,2021-08-25 05:02:55 UTC,CurateOffer_Result,"[{""curationProvider"":""ByPrice"",""offerId"":""149f..."
4,2021-09-05 08:03:28 UTC,DynamicPrice_Result,"{""provider"":""ApplyDynamicPriceRange"",""offerId""..."

In [19]:
# Parse the Payload
df['payload_parsed'] = df['Payload'].apply(json.loads)

# Convert Timezone
df["EnqueuedTimeUtc"] = pd.to_datetime(arg=df["EnqueuedTimeUtc"]).dt.tz_convert(tz="Brazil/East")

In [23]:
df.head()

,EnqueuedTimeUtc,EventName,Payload,payload_parsed
0,2021-09-05 05:04:08-03:00,DynamicPrice_Result,"{""provider"":""ApplyDynamicPriceRange"",""offerId""...","{'provider': 'ApplyDynamicPriceRange', 'offerI..."
1,2021-08-18 08:43:23-03:00,DynamicPrice_Result,"{""provider"":""ApplyDynamicPricePerOption"",""offe...","{'provider': 'ApplyDynamicPricePerOption', 'of..."
2,2021-09-05 06:04:04-03:00,DynamicPrice_Result,"{""provider"":""ApplyDynamicPriceRange"",""offerId""...","{'provider': 'ApplyDynamicPriceRange', 'offerI..."
3,2021-08-25 02:02:55-03:00,CurateOffer_Result,"[{""curationProvider"":""ByPrice"",""offerId"":""149f...","[{'curationProvider': 'ByPrice', 'offerId': '1..."
4,2021-09-05 05:03:28-03:00,DynamicPrice_Result,"{""provider"":""ApplyDynamicPriceRange"",""offerId""...","{'provider': 'ApplyDynamicPriceRange', 'offerI..."

In [25]:
dynamic_price_events = df[df["EventName"] == "DynamicPrice_Result"].copy()
dynamic_price_events.shape

(32, 4)

In [27]:
# DynamicPriceOption
def dynamic_price_option(row):
    """Transform the JSON payload into a dynamic price option dataframe."""
    enqueued_time = row["EnqueuedTimeUtc"].to_pydatetime().strftime("%d/%m/%y")
    payload_row = row["Payload"]
    payload_row = json.loads(payload_row)
    result = []
    if payload_row["provider"] == "ApplyDynamicPricePerOption":
        provider = f"\"{payload_row['provider']}\""
        offer_id = f"\"{payload_row['offerId']}\""
        for unique_option in payload_row["algorithmOutput"]:
            price_option = {
                "Provider": provider,
                "OfferId": offer_id,
                "UniqueOptionId": f"\"{unique_option['uniqueOptionId']}\"",
                "BestPrice": unique_option["bestPrice"],
                "EnqueuedTimeSP": enqueued_time
            }
            result.append(price_option)
    return result


lst = dynamic_price_events.apply(dynamic_price_option, axis=1)
flatten = [x for xs in lst for x in xs]
dynamic_price_option_payload = pd.DataFrame(flatten)

dynamic_price_option_payload

,Provider,OfferId,UniqueOptionId,BestPrice,EnqueuedTimeSP
0,"""ApplyDynamicPricePerOption""","""56e0702c-0218-4626-8d3d-ae9d54b4503b""","""b0e296a9-0590-f0e0-8211-243a2ededb12""",92.45,18/08/21
1,"""ApplyDynamicPricePerOption""","""56e0702c-0218-4626-8d3d-ae9d54b4503b""","""d6562c24-0b37-5fb4-8275-65b7b8b47b87""",92.45,18/08/21
2,"""ApplyDynamicPricePerOption""","""56e0702c-0218-4626-8d3d-ae9d54b4503b""","""8d0f9262-f543-d0c8-a869-33985ae3ecda""",92.45,18/08/21
3,"""ApplyDynamicPricePerOption""","""56e0702c-0218-4626-8d3d-ae9d54b4503b""","""151e59ac-761a-96f5-d2b9-882037a9fd28""",94.60,18/08/21
4,"""ApplyDynamicPricePerOption""","""56e0702c-0218-4626-8d3d-ae9d54b4503b""","""3cd346f4-d297-7568-2e50-d43a8e2fd0a9""",94.60,18/08/21
5,"""ApplyDynamicPricePerOption""","""56e0702c-0218-4626-8d3d-ae9d54b4503b""","""b7a7b6d1-4dae-7392-5aaf-f3369c29db1d""",93.00,18/08/21
6,"""ApplyDynamicPricePerOption""","""56e0702c-0218-4626-8d3d-ae9d54b4503b""","""577e4bbd-f49d-ac23-56a6-e70072a05229""",93.00,18/08/21
7,"""ApplyDynamicPricePerOption""","""56e0702c-0218-4626-8d3d-ae9d54b4503b""","""f9b876ab-2590-952f-d69d-5b352ec251f3""",91.35,18/08/21
8,"""ApplyDynamicPricePerOption""","""00991873-194e-4a6e-89c9-8f68668b6aaa""","""b0e296a9-0590-f0e0-8211-243a2ededb12""",92.45,18/08/21
9,"""ApplyDynamicPricePerOption""","""00991873-194e-4a6e-89c9-8f68668b6aaa""","""d6562c24-0b37-5fb4-8275-65b7b8b47b87""",92.45,18/08/21
10,"""ApplyDynamicPricePerOption""","""00991873-194e-4a6e-89c9-8f68668b6aaa""","""8d0f9262-f543-d0c8-a869-33985ae3ecda""",92.45,18/08/21
11,"""ApplyDynamicPricePerOption""","""00991873-194e-4a6e-89c9-8f68668b6aaa""","""151e59ac-761a-96f5-d2b9-882037a9fd28""",94.60,18/08/21
12,"""ApplyDynamicPricePerOption""","""00991873-194e-4a6e-89c9-8f68668b6aaa""","""3cd346f4-d297-7568-2e50-d43a8e2fd0a9""",94.60,18/08/21
13,"""ApplyDynamicPricePerOption""","""00991873-194e-4a6e-89c9-8f68668b6aaa""","""b7a7b6d1-4dae-7392-5aaf-f3369c29db1d""",93.00,18/08/21
14,"""ApplyDynamicPricePerOption""","""00991873-194e-4a6e-89c9-8f68668b6aaa""","""577e4bbd-f49d-ac23-56a6-e70072a05229""",93.00,18/08/21
15,"""ApplyDynamicPricePerOption""","""00991873-194e-4a6e-89c9-8f68668b6aaa""","""f9b876ab-2590-952f-d69d-5b352ec251f3""",91.35,18/08/21
16,"""ApplyDynamicPricePerOption""","""00991873-194e-4a6e-89c9-8f68668b6aaa""","""b0e296a9-0590-f0e0-8211-243a2ededb12""",92.45,18/08/21
17,"""ApplyDynamicPricePerOption""","""00991873-194e-4a6e-89c9-8f68668b6aaa""","""d6562c24-0b37-5fb4-8275-65b7b8b47b87""",92.45,18/08/21
18,"""ApplyDynamicPricePerOption""","""00991873-194e-4a6e-89c9-8f68668b6aaa""","""8d0f9262-f543-d0c8-a869-33985ae3ecda""",92.45,18/08/21
19,"""ApplyDynamicPricePerOption""","""00991873-194e-4a6e-89c9-8f68668b6aaa""","""151e59ac-761a-96f5-d2b9-882037a9fd28""",94.60,18/08/21
20,"""ApplyDynamicPricePerOption""","""00991873-194e-4a6e-89c9-8f68668b6aaa""","""3cd346f4-d297-7568-2e50-d43a8e2fd0a9""",94.60,18/08/21
21,"""ApplyDynamicPricePerOption""","""00991873-194e-4a6e-89c9-8f68668b6aaa""","""b7a7b6d1-4dae-7392-5aaf-f3369c29db1d""",93.00,18/08/21
22,"""ApplyDynamicPricePerOption""","""00991873-194e-4a6e-89c9-8f68668b6aaa""","""577e4bbd-f49d-ac23-56a6-e70072a05229""",93.00,18/08/21
23,"""ApplyDynamicPricePerOption""","""00991873-194e-4a6e-89c9-8f68668b6aaa""","""f9b876ab-2590-952f-d69d-5b352ec251f3""",91.35,18/08/21
24,"""ApplyDynamicPricePerOption""","""7a471a13-7922-4e7a-9667-9b2f96b44a2a""","""b0e296a9-0590-f0e0-8211-243a2ededb12""",92.45,18/08/21
25,"""ApplyDynamicPricePerOption""","""7a471a13-7922-4e7a-9667-9b2f96b44a2a""","""d6562c24-0b37-5fb4-8275-65b7b8b47b87""",92.45,18/08/21
26,"""ApplyDynamicPricePerOption""","""7a471a13-7922-4e7a-9667-9b2f96b44a2a""","""8d0f9262-f543-d0c8-a869-33985ae3ecda""",92.45,18/08/21
27,"""ApplyDynamicPricePerOption""","""7a471a13-7922-4e7a-9667-9b2f96b44a2a""","""151e59ac-761a-96f5-d2b9-882037a9fd28""",94.60,18/08/21
28,"""ApplyDynamicPricePerOption""","""7a471a13-7922-4e7a-9667-9b2f96b44a2a""","""3cd346f4-d297-7568-2e50-d43a8e2fd0a9""",94.60,18/08/21
29,"""ApplyDynamicPricePerOption""","""7a471a13-7922-4e7a-9667-9b2f96b44a2a""","""b7a7b6d1-4dae-7392-5aaf-f3369c29db1d""",93.00,18/08/21
30,"""ApplyDynamicPricePerOption""","""7a471a13-7922-4e7a-9667-9b2f96b44a2a""","""577e4bbd-f49d-ac23-56a6-e70072a05229""",93.00,18/08/21
31,"""ApplyDynamicPricePerOption""","""7a471a13-7922-4e7a-9667-9b2f96b44a2a""","""f9b876ab-2590-952f-d69d-5b352ec251f3""",91.35,18/08/21
32,"""ApplyDynamicPricePerOption""","""7cb20a39-c7f9-4c4c-9d51-94dbb8c4ff07""","""9c4ec643-934f-56d1-198d-46a8adc6c405""",93.50,18/08/21
33,"""ApplyDynamicPricePerOption""","""7cb20a39-c7f9-4c4c-9d51-94dbb8c4ff07""","""d6562c24-0b37-5fb4-8275-65b7b8b47b87""",93.50,18/08/21
34,"""ApplyDynamicPricePerOption""","""7cb20a39-c7f9-4c4c-9d51-94dbb8c4ff07""","""8d0f9262-f543-d0c8-a869-33985ae3ecda""",93.50,18/08/21
35,"""ApplyDynamicPricePerOption""","""7cb20a39-c7f9-4c4c-9d51-94dbb8c4ff07""","""151e59ac-761a-96f5-d2b9-882037a9fd28""",94.40,18/08/21
36,"""ApplyDynamicPricePerOption""","""7cb20a39-c7f9-4c4c-9d51-94dbb8c4ff07""","""3cd346f4-d297-7568-2e50-d43a8e2fd0a9""",94.40,18/08/21
37,"""ApplyDynamicPricePerOption""","""7cb20a39-c7f9-4c4c-9d51-94dbb8c4ff07""","""b7a7b6d1-4dae-7392-5aaf-f3369c29db1d""",94.40,18/08/21
38,"""ApplyDynamicPricePerOption""","""7cb20a39-c7f9-4c4c-9d51-94dbb8c4ff07""","""577e4bbd-f49d-ac23-56a6-e70072a05229""",94.40,18/08/21
39,"""ApplyDynamicPricePerOption""","""7cb20a39-c7f9-4c4c-9d51-94dbb8c4ff07""","""f9b876ab-2590-952f-d69d-5b352ec251f3""",93.95,18/08/21
40,"""ApplyDynamicPricePerOption""","""6dc306e7-7a6a-459a-a12c-400b4b3c9d37""","""b0e296a9-0590-f0e0-8211-243a2ededb12""",92.45,18/08/21
41,"""ApplyDynamicPricePerOption""","""6dc306e7-7a6a-459a-a12c-400b4b3c9d37""","""d6562c24-0b37-5fb4-8275-65b7b8b47b87""",92.45,18/08/21
42,"""ApplyDynamicPricePerOption""","""6dc306e7-7a6a-459a-a12c-400b4b3c9d37""","""8d0f9262-f543-d0c8-a869-33985ae3ecda""",92.45,18/08/21
43,"""ApplyDynamicPricePerOption""","""6dc306e7-7a6a-459a-a12c-400b4b3c9d37""","""151e59ac-761a-96f5-d2b9-882037a9fd28""",94.60,18/08/21
44,"""ApplyDynamicPricePerOption""","""6dc306e7-7a6a-459a-a12c-400b4b3c9d37""","""3cd346f4-d297-7568-2e50-d43a8e2fd0a9""",94.60,18/08/21
45,"""ApplyDynamicPricePerOption""","""6dc306e7-7a6a-459a-a12c-400b4b3c9d37""","""b7a7b6d1-4dae-7392-5aaf-f3369c29db1d""",93.00,18/08/21
46,"""ApplyDynamicPricePerOption""","""6dc306e7-7a6a-459a-a12c-400b4b3c9d37""","""577e4bbd-f49d-ac23-56a6-e70072a05229""",93.00,18/08/21
47,"""ApplyDynamicPricePerOption""","""6dc306e7-7a6a-459a-a12c-400b4b3c9d37""","""f9b876ab-2590-952f-d69d-5b352ec251f3""",91.35,18/08/21
48,"""ApplyDynamicPricePerOption""","""309e5beb-4e96-4f10-9233-e11057385c07""","""b0e296a9-0590-f0e0-8211-243a2ededb12""",92.45,18/08/21
49,"""ApplyDynamicPricePerOption""","""309e5beb-4e96-4f10-9233-e11057385c07""","""d6562c24-0b37-5fb4-8275-65b7b8b47b87""",92.45,18/08/21
50,"""ApplyDynamicPricePerOption""","""309e5beb-4e96-4f10-9233-e11057385c07""","""8d0f9262-f543-d0c8-a869-33985ae3ecda""",92.45,18/08/21
51,"""ApplyDynamicPricePerOption""","""309e5beb-4e96-4f10-9233-e11057385c07""","""151e59ac-761a-96f5-d2b9-882037a9fd28""",94.60,18/08/21
52,"""ApplyDynamicPricePerOption""","""309e5beb-4e96-4f10-9233-e11057385c07""","""3cd346f4-d297-7568-2e50-d43a8e2fd0a9""",94.60,18/08/21
53,"""ApplyDynamicPricePerOption""","""309e5beb-4e96-4f10-9233-e11057385c07""","""b7a7b6d1-4dae-7392-5aaf-f3369c29db1d""",93.00,18/08/21
54,"""ApplyDynamicPricePerOption""","""309e5beb-4e96-4f10-9233-e11057385c07""","""577e4bbd-f49d-ac23-56a6-e70072a05229""",93.00,18/08/21
55,"""ApplyDynamicPricePerOption""","""309e5beb-4e96-4f10-9233-e11057385c07""","""f9b876ab-2590-952f-d69d-5b352ec251f3""",91.35,18/08/21

In [29]:
# Dynamic Price Range
def dynamic_price_range(row):
    """Transform the JSON payload into a dynamic price range dataframe."""
    enqueued_time = row["EnqueuedTimeUtc"].to_pydatetime().strftime("%d/%m/%y")
    payload_row = row["Payload"]
    payload_row = json.loads(payload_row)
    result = []
    if payload_row["provider"] == "ApplyDynamicPriceRange":
        provider = f"\"{payload_row['provider']}\""
        offer_id = f"\"{payload_row['offerId']}\""
        algorithm_output = payload_row["algorithmOutput"]
        price_range = {
            "Provider": provider,
            "OfferId": offer_id,
            "MinGlobal": algorithm_output["min_global"],
            "MinRecommended": algorithm_output["min_recommended"],
            "MaxRecommended": algorithm_output["max_recommended"],
            "DifferenceMinRecommendMinTheory": algorithm_output["differenceMinRecommendMinTheory"],
            "EnqueuedTimeSP": enqueued_time
        }
        result.append(price_range)
    return result

lst_range = dynamic_price_events.apply(dynamic_price_range, axis=1)
flatten_range = [x for xs in lst_range for x in xs]
dynamic_price_range_payload = pd.DataFrame(flatten_range)

dynamic_price_range_payload

,Provider,OfferId,MinGlobal,MinRecommended,MaxRecommended,DifferenceMinRecommendMinTheory,EnqueuedTimeSP
0,"""ApplyDynamicPriceRange""","""a6611d55-9624-4381-8cdd-323ee3689241""",85.00,87.20,97.65,2.2,05/09/21
1,"""ApplyDynamicPriceRange""","""b8c636fa-8241-47dc-ac40-bdf438a04d9c""",85.00,87.20,97.65,2.2,05/09/21
2,"""ApplyDynamicPriceRange""","""3d32f7fb-396d-4d3f-b673-dea1f7dc41b7""",85.00,87.20,97.65,2.2,05/09/21
3,"""ApplyDynamicPriceRange""","""329194f3-95a4-45ef-b3d0-2796f74ce2a0""",85.00,87.20,97.65,2.2,05/09/21
4,"""ApplyDynamicPriceRange""","""fdcfde5c-113d-4a59-9ae0-8bc31e2943d8""",87.35,89.25,99.95,1.9,05/09/21
5,"""ApplyDynamicPriceRange""","""27bbc4fa-2388-4780-b66c-92a51397d191""",87.35,89.25,99.95,1.9,05/09/21
6,"""ApplyDynamicPriceRange""","""baffc30b-7642-45fe-a2ce-da31a71732ae""",85.00,87.20,97.65,2.2,05/09/21
7,"""ApplyDynamicPriceRange""","""b5982abd-f602-47ac-b45a-bb43bf993d46""",85.00,87.20,97.65,2.2,05/09/21
8,"""ApplyDynamicPriceRange""","""f6643886-4a0f-45ae-ae32-ee95c72ee94a""",87.35,89.25,99.95,1.9,05/09/21
9,"""ApplyDynamicPriceRange""","""16a2d492-b1c3-40ec-970f-b8704d8db96f""",85.00,87.20,97.65,2.2,05/09/21
10,"""ApplyDynamicPriceRange""","""e94cf567-d77a-4874-9663-0b49d19f604c""",85.00,87.20,97.65,2.2,05/09/21
11,"""ApplyDynamicPriceRange""","""57a52d66-93fb-40a4-b44a-662d439ce070""",85.00,87.20,97.65,2.2,05/09/21
12,"""ApplyDynamicPriceRange""","""0474ba06-1a1e-4ebe-934f-b416dd0c9313""",87.35,89.25,99.95,1.9,05/09/21
13,"""ApplyDynamicPriceRange""","""a48a4485-1add-468e-9f20-5b3659498b82""",85.00,87.20,97.65,2.2,05/09/21
14,"""ApplyDynamicPriceRange""","""d7739a03-c1f8-46db-971f-1a9af3dd88d9""",87.35,89.25,99.95,1.9,05/09/21
15,"""ApplyDynamicPriceRange""","""4e44bf19-62ff-4d6e-8ce6-f4de80bb027d""",85.00,87.20,97.65,2.2,05/09/21
16,"""ApplyDynamicPriceRange""","""3da3a438-3fd3-432a-a778-e0a2d815f831""",87.35,89.25,99.95,1.9,05/09/21
17,"""ApplyDynamicPriceRange""","""bc8a4008-eef4-4059-8264-a078f618f3bd""",85.00,87.20,97.65,2.2,05/09/21
18,"""ApplyDynamicPriceRange""","""36d3b55c-a449-4ab3-9b49-849d158038da""",85.00,87.20,97.65,2.2,05/09/21
19,"""ApplyDynamicPriceRange""","""5ebc735e-7445-4d17-aeca-b56d8d04a51a""",85.00,87.20,97.65,2.2,05/09/21
20,"""ApplyDynamicPriceRange""","""31cc86f1-881b-4b89-838e-bffdcfded61e""",85.00,87.20,97.65,2.2,05/09/21
21,"""ApplyDynamicPriceRange""","""7e7f25c6-6352-40d0-bd1e-1dd4e8a5c222""",85.00,87.20,97.65,2.2,05/09/21
22,"""ApplyDynamicPriceRange""","""c0b7cf25-62d1-4f3d-be18-3825c316ed8d""",85.00,87.20,97.65,2.2,05/09/21
23,"""ApplyDynamicPriceRange""","""de8394da-020c-422a-890a-0d77a5f8359a""",85.00,87.20,97.65,2.2,05/09/21
24,"""ApplyDynamicPriceRange""","""92269c83-9103-4ea3-b93b-ae2f1762f720""",85.00,87.20,97.65,2.2,05/09/21

In [30]:
curated_offers = df[df["EventName"] == "CurateOffer_Result"]
curated_offers.shape

(5, 4)

In [35]:
def curated_offer(row):
    """Transform JSON payload into curated offer dataframe."""
    enqueued_time = row["EnqueuedTimeUtc"].to_pydatetime().strftime("%d/%m/%y")
    payload_row = row["Payload"]
    payload_row = json.loads(payload_row)
    result = []
    for el in payload_row:
        curation_provider = f"\"{el['curationProvider']}\""
        offer_id = f"\"{el['offerId']}\""
        dealer_id = f"\"{el['dealerId']}\""
        for option in el["options"]:
            offer_options = {
                "CurationProvider": curation_provider,
                "OfferId": offer_id,
                "DealerId": dealer_id,
                "UniqueOptionId": f"\"{option['uniqueOptionId']}\"",
                "OptionId": f"\"{option['optionId']}\"",
                "IsMobileDealer": option["isMobileDealer"],
                "IsOpen": option["isOpen"],
                "Eta": f"\"{option['eta']}\"",
                "ChamaScore": option["chamaScore"],
                "ProductBrand": f"\"{option['productBrand']}\"",
                "IsWinner": option["isWinner"],
                "MinimumPrice": option["minimumPrice"],
                "MaximumPrice": option["maximumPrice"],
                "DynamicPrice": option["dynamicPrice"],
                "FinalPrice": option["finalPrice"]
            }
            if "defeatPrimaryReason" in option:
                offer_options["DefeatPrimaryReason"] = f"\"{option['defeatPrimaryReason']}\""
                offer_options["DefeatReasons"] = f"\"{option['defeatReasons']}\""
            else:
                offer_options["DefeatPrimaryReason"] = "\"\""
                offer_options["DefeatReasons"] = "\"\""
            offer_options["EnqueuedTimeSP"] = enqueued_time
            result.append(offer_options)
    return result


flatten_curated = [x for xs in curated_offers.apply(curated_offer, axis=1) for x in xs]
curated_offers_payload = pd.DataFrame(flatten_curated)

curated_offers_payload

,CurationProvider,OfferId,DealerId,UniqueOptionId,OptionId,IsMobileDealer,IsOpen,Eta,ChamaScore,ProductBrand,IsWinner,MinimumPrice,MaximumPrice,DynamicPrice,FinalPrice,DefeatPrimaryReason,DefeatReasons,EnqueuedTimeSP
0,"""ByPrice""","""149f0e53-ff85-425f-a01a-8710f06704ea""","""6517""","""b0e296a9-0590-f0e0-8211-243a2ededb12""","""6517 || dd839e4c-9f84-45eb-9cb2-9069fecf70f2""",True,True,"""1:00""",8.0,"""ULTRAGAZ""",True,90.00,180.00,91.90,91.90,"""""","""""",25/08/21
1,"""ByPrice""","""149f0e53-ff85-425f-a01a-8710f06704ea""","""6517""","""d6562c24-0b37-5fb4-8275-65b7b8b47b87""","""6517 || 6517""",False,False,"""0:01""",8.0,"""ULTRAGAZ""",False,90.00,180.00,91.90,91.90,"""Closed""","""['Closed', 'HasDriverInOffer']""",25/08/21
2,"""ByPrice""","""149f0e53-ff85-425f-a01a-8710f06704ea""","""9047""","""8d0f9262-f543-d0c8-a869-33985ae3ecda""","""9047 || 9047 || ULTRAGAZ""",False,False,"""1:00""",9.0,"""ULTRAGAZ""",False,99.00,198.00,99.95,99.95,"""Closed""","""['Closed', 'HigherPrice', 'HasDriverInOffer']""",25/08/21
3,"""ByPrice""","""149f0e53-ff85-425f-a01a-8710f06704ea""","""9047""","""3cd346f4-d297-7568-2e50-d43a8e2fd0a9""","""9047 || 9047 || CONSIGAZ""",False,False,"""1:00""",9.0,"""CONSIGAZ""",False,89.99,179.98,91.89,91.89,"""Closed""","""['Closed', 'HigherPrice', 'HigherETA']""",25/08/21
4,"""ByPrice""","""149f0e53-ff85-425f-a01a-8710f06704ea""","""9047""","""577e4bbd-f49d-ac23-56a6-e70072a05229""","""9047 || 9047 || LIQUIGAS""",False,False,"""1:00""",9.0,"""LIQUIGAS""",False,92.00,184.00,93.90,93.90,"""Closed""","""['Closed', 'HigherPrice', 'HigherETA']""",25/08/21
5,"""ByPrice""","""149f0e53-ff85-425f-a01a-8710f06704ea""","""9047""","""f9b876ab-2590-952f-d69d-5b352ec251f3""","""9047 || 9047 || NACIONALGAS""",False,False,"""1:00""",9.0,"""NACIONALGAS""",True,88.90,177.80,90.80,90.80,"""""","""""",25/08/21
6,"""ByPrice""","""149f0e53-ff85-425f-a01a-8710f06704ea""","""8330""","""151e59ac-761a-96f5-d2b9-882037a9fd28""","""8330 || 8330 || CONSIGAZ""",False,True,"""0:01""",8.0,"""CONSIGAZ""",True,80.00,160.00,87.35,87.35,"""""","""""",25/08/21
7,"""ByPrice""","""149f0e53-ff85-425f-a01a-8710f06704ea""","""8835""","""b7a7b6d1-4dae-7392-5aaf-f3369c29db1d""","""8835 || 8835 || LIQUIGAS""",False,False,"""0:01""",8.0,"""LIQUIGAS""",True,60.00,120.00,87.35,87.35,"""""","""""",25/08/21
8,"""ByPrice""","""c99aa9a7-ac50-4a10-be0f-ac9f5ac0f45d""","""6517""","""b0e296a9-0590-f0e0-8211-243a2ededb12""","""6517 || dd839e4c-9f84-45eb-9cb2-9069fecf70f2""",True,True,"""00:12:54.9215999""",8.0,"""ULTRAGAZ""",True,90.00,180.00,91.90,91.90,"""""","""""",25/08/21
9,"""ByPrice""","""c99aa9a7-ac50-4a10-be0f-ac9f5ac0f45d""","""6517""","""d6562c24-0b37-5fb4-8275-65b7b8b47b87""","""6517 || 6517""",False,True,"""0:01""",8.0,"""ULTRAGAZ""",False,90.00,180.00,91.90,91.90,"""HasDriverInOffer""","""['HasDriverInOffer']""",25/08/21
10,"""ByPrice""","""c99aa9a7-ac50-4a10-be0f-ac9f5ac0f45d""","""9047""","""8d0f9262-f543-d0c8-a869-33985ae3ecda""","""9047 || 9047 || ULTRAGAZ""",False,False,"""1:00""",9.0,"""ULTRAGAZ""",False,99.00,198.00,99.95,99.95,"""Closed""","""['Closed', 'HigherPrice', 'HasDriverInOffer',...",25/08/21
11,"""ByPrice""","""c99aa9a7-ac50-4a10-be0f-ac9f5ac0f45d""","""9047""","""3cd346f4-d297-7568-2e50-d43a8e2fd0a9""","""9047 || 9047 || CONSIGAZ""",False,False,"""1:00""",9.0,"""CONSIGAZ""",False,89.99,179.98,91.89,91.89,"""Closed""","""['Closed', 'HigherPrice', 'HigherETA']""",25/08/21
12,"""ByPrice""","""c99aa9a7-ac50-4a10-be0f-ac9f5ac0f45d""","""9047""","""577e4bbd-f49d-ac23-56a6-e70072a05229""","""9047 || 9047 || LIQUIGAS""",False,False,"""1:00""",9.0,"""LIQUIGAS""",False,92.00,184.00,93.90,93.90,"""Closed""","""['Closed', 'HigherPrice', 'HigherETA']""",25/08/21
13,"""ByPrice""","""c99aa9a7-ac50-4a10-be0f-ac9f5ac0f45d""","""9047""","""f9b876ab-2590-952f-d69d-5b352ec251f3""","""9047 || 9047 || NACIONALGAS""",False,False,"""1:00""",9.0,"""NACIONALGAS""",True,88.90,177.80,90.80,90.80,"""""","""""",25/08/21
14,"""ByPrice""","""c99aa9a7-ac50-4a10-be0f-ac9f5ac0f45d""","""8330""","""151e59ac-761a-96f5-d2b9-882037a9fd28""","""8330 || 8330 || CONSIGAZ""",False,True,"""0:01""",8.0,"""CONSIGAZ""",True,80.00,160.00,87.35,87.35,"""""","""""",25/08/21
15,"""ByPrice""","""c99aa9a7-ac50-4a10-be0f-ac9f5ac0f45d""","""8835""","""b7a7b6d1-4dae-7392-5aaf-f3369c29db1d""","""8835 || 8835 || LIQUIGAS""",False,False,"""0:01""",8.0,"""LIQUIGAS""",True,60.00,120.00,87.35,87.35,"""""","""""",25/08/21
16,"""ByPrice""","""d668106a-7596-49c6-b99a-18b7a2f3963f""","""6517""","""b0e296a9-0590-f0e0-8211-243a2ededb12""","""6517 || dd839e4c-9f84-45eb-9cb2-9069fecf70f2""",True,True,"""1:00""",8.0,"""ULTRAGAZ""",True,90.00,180.00,91.90,91.90,"""""","""""",25/08/21
17,"""ByPrice""","""d668106a-7596-49c6-b99a-18b7a2f3963f""","""6517""","""d6562c24-0b37-5fb4-8275-65b7b8b47b87""","""6517 || 6517""",False,False,"""0:01""",8.0,"""ULTRAGAZ""",False,90.00,180.00,91.90,91.90,"""Closed""","""['Closed', 'HasDriverInOffer']""",25/08/21
18,"""ByPrice""","""d668106a-7596-49c6-b99a-18b7a2f3963f""","""9047""","""8d0f9262-f543-d0c8-a869-33985ae3ecda""","""9047 || 9047 || ULTRAGAZ""",False,False,"""1:00""",9.0,"""ULTRAGAZ""",False,99.00,198.00,99.95,99.95,"""Closed""","""['Closed', 'HigherPrice', 'HasDriverInOffer']""",25/08/21
19,"""ByPrice""","""d668106a-7596-49c6-b99a-18b7a2f3963f""","""9047""","""3cd346f4-d297-7568-2e50-d43a8e2fd0a9""","""9047 || 9047 || CONSIGAZ""",False,False,"""1:00""",9.0,"""CONSIGAZ""",False,89.99,179.98,91.89,91.89,"""Closed""","""['Closed', 'HigherPrice', 'HigherETA']""",25/08/21
20,"""ByPrice""","""d668106a-7596-49c6-b99a-18b7a2f3963f""","""9047""","""577e4bbd-f49d-ac23-56a6-e70072a05229""","""9047 || 9047 || LIQUIGAS""",False,False,"""1:00""",9.0,"""LIQUIGAS""",False,92.00,184.00,93.90,93.90,"""Closed""","""['Closed', 'HigherPrice', 'HigherETA']""",25/08/21
21,"""ByPrice""","""d668106a-7596-49c6-b99a-18b7a2f3963f""","""9047""","""f9b876ab-2590-952f-d69d-5b352ec251f3""","""9047 || 9047 || NACIONALGAS""",False,False,"""1:00""",9.0,"""NACIONALGAS""",True,88.90,177.80,90.80,90.80,"""""","""""",25/08/21
22,"""ByPrice""","""d668106a-7596-49c6-b99a-18b7a2f3963f""","""8330""","""151e59ac-761a-96f5-d2b9-882037a9fd28""","""8330 || 8330 || CONSIGAZ""",False,True,"""0:01""",8.0,"""CONSIGAZ""",True,80.00,160.00,87.35,87.35,"""""","""""",25/08/21
23,"""ByPrice""","""d668106a-7596-49c6-b99a-18b7a2f3963f""","""8835""","""b7a7b6d1-4dae-7392-5aaf-f3369c29db1d""","""8835 || 8835 || LIQUIGAS""",False,False,"""0:01""",8.0,"""LIQUIGAS""",True,60.00,120.00,87.35,87.35,"""""","""""",25/08/21
24,"""ByPrice""","""0a06a478-77b3-4941-83d3-84ded18d4731""","""6517""","""b0e296a9-0590-f0e0-8211-243a2ededb12""","""6517 || dd839e4c-9f84-45eb-9cb2-9069fecf70f2""",True,True,"""00:01:27.4607999""",8.0,"""ULTRAGAZ""",True,90.00,180.00,91.90,91.90,"""""","""""",25/08/21
25,"""ByPrice""","""0a06a478-77b3-4941-83d3-84ded18d4731""","""6517""","""d6562c24-0b37-5fb4-8275-65b7b8b47b87""","""6517 || 6517""",False,True,"""0:01""",8.0,"""ULTRAGAZ""",False,90.00,180.00,91.90,91.90,"""HasDriverInOffer""","""['HasDriverInOffer']""",25/08/21
26,"""ByPrice""","""0a06a478-77b3-4941-83d3-84ded18d4731""","""9047""","""8d0f9262-f543-d0c8-a869-33985ae3ecda""","""9047 || 9047 || ULTRAGAZ""",False,False,"""1:00""",9.0,"""ULTRAGAZ""",False,99.00,198.00,99.95,99.95,"""Closed""","""['Closed', 'HigherPrice', 'HasDriverInOffer',...",25/08/21
27,"""ByPrice""","""0a06a478-77b3-4941-83d3-84ded18d4731""","""9047""","""3cd346f4-d297-7568-2e50-d43a8e2fd0a9""","""9047 || 9047 || CONSIGAZ""",False,False,"""1:00""",9.0,"""CONSIGAZ""",False,89.99,179.98,91.89,91.89,"""Closed""","""['Closed', 'HigherPrice', 'HigherETA']""",25/08/21
28,"""ByPrice""","""0a06a478-77b3-4941-83d3-84ded18d4731""","""9047""","""577e4bbd-f49d-ac23-56a6-e70072a05229""","""9047 || 9047 || LIQUIGAS""",False,False,"""1:00""",9.0,"""LIQUIGAS""",False,92.00,184.00,93.90,93.90,"""Closed""","""['Closed', 'HigherPrice', 'HigherETA']""",25/08/21
29,"""ByPrice""","""0a06a478-77b3-4941-83d3-84ded18d4731""","""9047""","""f9b876ab-2590-952f-d69d-5b352ec251f3""","""9047 || 9047 || NACIONALGAS""",False,False,"""1:00""",9.0,"""NACIONALGAS""",True,88.90,177.80,90.80,90.80,"""""","""""",25/08/21
30,"""ByPrice""","""0a06a478-77b3-4941-83d3-84ded18d4731""","""8330""","""151e59ac-761a-96f5-d2b9-882037a9fd28""","""8330 || 8330 || CONSIGAZ""",False,True,"""0:01""",8.0,"""CONSIGAZ""",True,80.00,160.00,87.35,87.35,"""""","""""",25/08/21
31,"""ByPrice""","""0a06a478-77b3-4941-83d3-84ded18d4731""","""8835""","""b7a7b6d1-4dae-7392-5aaf-f3369c29db1d""","""8835 || 8835 || LIQUIGAS""",False,False,"""0:01""",8.0,"""LIQUIGAS""",True,60.00,120.00,87.35,87.35,"""""","""""",25/08/21
32,"""ByPrice""","""135d8401-11c0-4d21-bac1-cdb93ba65189""","""6517""","""b0e296a9-0590-f0e0-8211-243a2ededb12""","""6517 || dd839e4c-9f84-45eb-9cb2-9069fecf70f2""",True,True,"""00:07:11.1911999""",8.0,"""ULTRAGAZ""",True,90.00,180.00,91.90,91.90,"""""","""""",25/08/21
33,"""ByPrice""","""135d8401-11c0-4d21-bac1-cdb93ba65189""","""6517""","""d6562c24-0b37-5fb4-8275-65b7b8b47b87""","""6517 || 6517""",False,True,"""0:01""",8.0,"""ULTRAGAZ""",False,90.00,180.00,91.90,91.90,"""HasDriverInOffer""","""['HasDriverInOffer']""",25/08/21
34,"""ByPrice""","""135d8401-11c0-4d21-bac1-cdb93ba65189""","""9047""","""8d0f9262-f543-d0c8-a869-33985ae3ecda""","""9047 || 9047 || ULTRAGAZ""",False,False,"""1:00""",9.0,"""ULTRAGAZ""",False,99.00,198.00,99.95,99.95,"""Closed""","""['Closed', 'HigherPrice', 'HasDriverInOffer',...",25/08/21
35,"""ByPrice""","""135d8401-11c0-4d21-bac1-cdb93ba65189""","""9047""","""3cd346f4-d297-7568-2e50-d43a8e2fd0a9""","""9047 || 9047 || CONSIGAZ""",False,False,"""1:00""",9.0,"""CONSIGAZ""",False,89.99,179.98,91.89,91.89,"""Closed""","""['Closed', 'HigherPrice', 'HigherETA']""",25/08/21
36,"""ByPrice""","""135d8401-11c0-4d21-bac1-cdb93ba65189""","""9047""","""577e4bbd-f49d-ac23-56a6-e70072a05229""","""9047 || 9047 || LIQUIGAS""",False,False,"""1:00""",9.0,"""LIQUIGAS""",False,92.00,184.00,93.90,93.90,"""Closed""","""['Closed', 'HigherPrice', 'HigherETA']""",25/08/21
37,"""ByPrice""","""135d8401-11c0-4d21-bac1-cdb93ba65189""","""9047""","""f9b876ab-2590-952f-d69d-5b352ec251f3""","""9047 || 9047 || NACIONALGAS""",False,False,"""1:00""",9.0,"""NACIONALGAS""",True,88.90,177.80,90.80,90.80,"""""","""""",25/08/21
38,"""ByPrice""","""135d8401-11c0-4d21-bac1-cdb93ba65189""","""8330""","""151e59ac-761a-96f5-d2b9-882037a9fd28""","""8330 || 8330 || CONSIGAZ""",False,True,"""0:01""",8.0,"""CONSIGAZ""",True,80.00,160.00,87.35,87.35,"""""","""""",25/08/21
39,"""ByPrice""","""135d8401-11c0-4d21-bac1-cdb93ba65189""","""8835""","""b7a7b6d1-4dae-7392-5aaf-f3369c29db1d""","""8835 || 8835 || LIQUIGAS""",False,False,"""0:01""",8.0,"""LIQUIGAS""",True,60.00,120.00,87.35,87.35,"""""","""""",25/08/21

In [34]:
dynamic_price_option_payload.to_csv("dynamic_price_option_payload.csv", index=False)
dynamic_price_range_payload.to_csv("dynamic_price_range_payload.csv", index=False)
curated_offers_payload.to_csv("curated_offers_payload.csv", index=False)